/**
 * Single source of truth for page categories.
 *
 * Both the Nuxt app (composables, components, pages) and the Reddit pipeline
 * (`scripts/reddit-pipeline`) import this module, so the vocabulary can never
 * drift between the content, the agents and the UI.
 *
 * The categories are split into two groups:
 *
 * - {@link PROJECT_CATEGORIES} — concrete projects (games and apps) that are
 *   listed on the site and generated by the create/update agents.
 * - {@link SYSTEM_CATEGORIES} — static, hand-written pages that are not
 *   projects and are excluded from the project listing and filtering.
 */

/**
 * Project categories — every entry describes a concrete project (game or app)
 * that can be listed on the site and generated by the create/update agents.
 *
 * - `game` — a standalone, self-contained game.
 * - `app` — a standalone application that makes use of both screens.
 * - `companion` — an app used together with a game to show useful information;
 *   it may be synced with the game in real time or act as an offline reference.
 * - `emulator` — an emulator of a system that has a feature using the second
 *   screen.
 * - `tool` — a utility for flexible configuration or for improving how the
 *   system works overall.
 */
export const PROJECT_CATEGORIES = [
  'game',
  'app',
  'companion',
  'emulator',
  'tool',
] as const;

/**
 * System categories — static, hand-written pages that are not projects and are
 * excluded from the project listing and filtering.
 *
 * - `page` — a static, system page (e.g. the how-to guide).
 */
export const SYSTEM_CATEGORIES = ['page'] as const;

/** Every valid `category` value of a content page (projects + system pages). */
export const PAGE_CATEGORIES = [
  ...PROJECT_CATEGORIES,
  ...SYSTEM_CATEGORIES,
] as const;

/** A project category (one of {@link PROJECT_CATEGORIES}). */
export type ProjectCategory = (typeof PROJECT_CATEGORIES)[number];

/** A system category (one of {@link SYSTEM_CATEGORIES}). */
export type SystemCategory = (typeof SYSTEM_CATEGORIES)[number];

/** Any valid page category (one of {@link PAGE_CATEGORIES}). */
export type PageCategory = (typeof PAGE_CATEGORIES)[number];

/**
 * Human-readable definition of every category. Kept next to the vocabulary so
 * the agents, the docs and the UI all describe the categories the same way.
 */
export const CATEGORY_DEFINITIONS: Record<PageCategory, string> = {
  game: 'A standalone, self-contained game.',
  app: 'A standalone application that makes use of both screens.',
  companion:
    'An app used together with a game to show useful information. It may be synced with the game in real time or act as an offline reference.',
  emulator:
    'An emulator of a system that has a feature using the second screen.',
  tool: 'A utility for flexible configuration or for improving how the system works overall.',
  page: 'A static, system page (e.g. the how-to guide). Not a project.',
};

/** Short labels for the category filter UI. */
export const CATEGORY_LABELS: Record<PageCategory, string> = {
  game: 'Games',
  app: 'Apps',
  companion: 'Companions',
  emulator: 'Emulators',
  tool: 'Tools',
  page: 'Pages',
};

/** Set view of {@link PROJECT_CATEGORIES} for fast membership checks. */
const PROJECT_CATEGORY_SET = new Set<string>(PROJECT_CATEGORIES);

/** Set view of {@link SYSTEM_CATEGORIES} for fast membership checks. */
const SYSTEM_CATEGORY_SET = new Set<string>(SYSTEM_CATEGORIES);

/** Set view of {@link PAGE_CATEGORIES} for fast membership checks. */
const PAGE_CATEGORY_SET = new Set<string>(PAGE_CATEGORIES);

/** Type guard: is `value` a project category? */
export function isProjectCategory(value: unknown): value is ProjectCategory {
  return typeof value === 'string' && PROJECT_CATEGORY_SET.has(value);
}

/** Type guard: is `value` a system category? */
export function isSystemCategory(value: unknown): value is SystemCategory {
  return typeof value === 'string' && SYSTEM_CATEGORY_SET.has(value);
}

/** Type guard: is `value` any valid page category? */
export function isPageCategory(value: unknown): value is PageCategory {
  return typeof value === 'string' && PAGE_CATEGORY_SET.has(value);
}
