/**
 * Single source of truth for page categories.
 *
 * Both the Nuxt app (composables, components, pages) and the Reddit pipeline
 * (`scripts/reddit-pipeline`) import this module, so the vocabulary can never
 * drift between the content, the agents and the UI.
 *
 * The categories are split into two groups:
 *
 * - {@link PROJECT_CATEGORIES} — concrete projects (games and apps) that are
 *   listed on the site and generated by the create/update agents.
 * - {@link SYSTEM_CATEGORIES} — static, hand-written pages that are not
 *   projects and are excluded from the project listing and filtering.
 */

/**
 * Project categories — every entry describes a concrete project (game or app)
 * that can be listed on the site and generated by the create/update agents.
 *
 * - `game` — a standalone, self-contained game.
 * - `app` — a standalone application that makes use of both screens.
 * - `companion` — an app used together with a game to show useful information;
 *   it may be synced with the game in real time or act as an offline reference.
 * - `emulator` — an emulator of a system that has a feature using the second
 *   screen.
 * - `tool` — a utility for flexible configuration or for improving how the
 *   system works overall.
 */
export const PROJECT_CATEGORIES = [
  'game',
  'app',
  'companion',
  'emulator',
  'tool',
] as const;

/**
 * System categories — static, hand-written pages that are not projects and are
 * excluded from the project listing and filtering.
 *
 * - `page` — a static, system page (e.g. the how-to guide).
 */
export const SYSTEM_CATEGORIES = ['page'] as const;

/** Every valid `category` value of a content page (projects + system pages). */
export const PAGE_CATEGORIES = [
  ...PROJECT_CATEGORIES,
  ...SYSTEM_CATEGORIES,
] as const;

/** A project category (one of {@link PROJECT_CATEGORIES}). */
export type ProjectCategory = (typeof PROJECT_CATEGORIES)[number];

/** A system category (one of {@link SYSTEM_CATEGORIES}). */
export type SystemCategory = (typeof SYSTEM_CATEGORIES)[number];

/** Any valid page category (one of {@link PAGE_CATEGORIES}). */
export type PageCategory = (typeof PAGE_CATEGORIES)[number];

/**
 * Human-readable definition of every category. Kept next to the vocabulary so
 * the agents, the docs and the UI all describe the categories the same way.
 */
export const CATEGORY_DEFINITIONS: Record<PageCategory, string> = {
  game: 'A standalone, self-contained game.',
  app: 'A standalone application that makes use of both screens.',
  companion:
    'An app used together with a game to show useful information. It may be synced with the game in real time or act as an offline reference.',
  emulator:
    'An emulator of a system that has a feature using the second screen.',
  tool: 'A utility for flexible configuration or for improving how the system works overall.',
  page: 'A static, system page (e.g. the how-to guide). Not a project.',
};

/** Short labels for the category filter UI. */
export const CATEGORY_LABELS: Record<PageCategory, string> = {
  game: 'Games',
  app: 'Apps',
  companion: 'Companions',
  emulator: 'Emulators',
  tool: 'Tools',
  page: 'Pages',
};

/**
 * Color theme of a category badge/chip.
 *
 * The UI does not use Tailwind utility classes here on purpose — colors are
 * applied as inline styles so a category can be recolored in a single place
 * without having to safelist dynamically-built class names.
 *
 * - `text` — foreground (label / dot) color.
 * - `bg` — translucent background for the inactive state.
 * - `border` — border color.
 */
export interface CategoryColor {
  text: string;
  bg: string;
  border: string;
}

/**
 * Configurable color map: every category has its own color. Tweak the values
 * here to recolor badges and filter chips across the whole site.
 */
export const CATEGORY_COLORS: Record<PageCategory, CategoryColor> = {
  game: { text: '#8aa4c8', bg: 'rgba(138, 164, 200, 0.10)', border: 'rgba(138, 164, 200, 0.28)' },
  app: { text: '#8fb89a', bg: 'rgba(143, 184, 154, 0.10)', border: 'rgba(143, 184, 154, 0.28)' },
  companion: { text: '#c9b98a', bg: 'rgba(201, 185, 138, 0.10)', border: 'rgba(201, 185, 138, 0.28)' },
  emulator: { text: '#a99bc4', bg: 'rgba(169, 155, 196, 0.10)', border: 'rgba(169, 155, 196, 0.28)' },
  tool: { text: '#c795a5', bg: 'rgba(199, 149, 165, 0.10)', border: 'rgba(199, 149, 165, 0.28)' },
  page: { text: '#8fb8b0', bg: 'rgba(143, 184, 176, 0.10)', border: 'rgba(143, 184, 176, 0.28)' },
};

/** Neutral fallback used when a page has an unknown category value. */
const FALLBACK_CATEGORY_COLOR: CategoryColor = {
  text: '#8b93a7',
  bg: 'rgba(139, 147, 167, 0.10)',
  border: 'rgba(139, 147, 167, 0.28)',
};

/** Resolve the color theme for an arbitrary category string (safe fallback). */
export function getCategoryColor(category: string): CategoryColor {
  return isPageCategory(category) ? CATEGORY_COLORS[category] : FALLBACK_CATEGORY_COLOR;
}

/** Resolve the short label for an arbitrary category string (safe fallback). */
export function getCategoryLabel(category: string): string {
  return isPageCategory(category) ? CATEGORY_LABELS[category] : category;
}

/** Set view of {@link PROJECT_CATEGORIES} for fast membership checks. */
const PROJECT_CATEGORY_SET = new Set<string>(PROJECT_CATEGORIES);

/** Set view of {@link SYSTEM_CATEGORIES} for fast membership checks. */
const SYSTEM_CATEGORY_SET = new Set<string>(SYSTEM_CATEGORIES);

/** Set view of {@link PAGE_CATEGORIES} for fast membership checks. */
const PAGE_CATEGORY_SET = new Set<string>(PAGE_CATEGORIES);

/** Type guard: is `value` a project category? */
export function isProjectCategory(value: unknown): value is ProjectCategory {
  return typeof value === 'string' && PROJECT_CATEGORY_SET.has(value);
}

/** Type guard: is `value` a system category? */
export function isSystemCategory(value: unknown): value is SystemCategory {
  return typeof value === 'string' && SYSTEM_CATEGORY_SET.has(value);
}

/** Type guard: is `value` any valid page category? */
export function isPageCategory(value: unknown): value is PageCategory {
  return typeof value === 'string' && PAGE_CATEGORY_SET.has(value);
}
